[profile.default]
solc = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "write", path = "./deployments" }
]
# 优化器配置
optimizer = true
optimizer_runs = 200
sepolia = "${SEPOLIA_RPC_URL}"
local = "${LOCAL_URL}"
private_key = "${PRIVATE_KEY}"
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options







